### ISSUE TITLE
Savior Bonuses not adding properly to Characters

### ISSUE THREAD

**Issue by lajollagrad** [Playing-Indoors/KDM_WWW#100]
Issue: When clicking on "Dream of the X" to denote your savior and get the bonuses all set up under abiilities, it looks like there is logic to add ALL of the bonuses acquired when that happens. Unfortunately, the first time you click on the ability and click confirm, it only populates with the one ability. When you go back in there and actually click cancel, it populates with all of the abilities. Shouldn't need to go back in to do this as it should populate everything or perhaps ask you if you would like to populate the rest of the abilities. Clicking cancel shouldn't be the only way to get this to happen.

![saviors bonuses not expanded](https://user-images.githubusercontent.com/34521900/33961066-8cb5b1d2-e001-11e7-90ad-2bb4186d2ec4.JPG)

![saviors bonuses expanded](https://user-images.githubusercontent.com/34521900/33961069-90c054b2-e001-11e7-9409-f11fa72ed42f.JPG)

**Comment by toconnell** [comment]
@CalebKester If you look at these assets, they've got a special key/value `selectable: false`:

```
    "dormenatus": {
        "handle": "dormenatus",
        "max": 1,
        "epithet": "dormenatus",
        "related": [
            "dream_of_the_crown",
            "life_exchange"
        ],
        "type_pretty": "Abilities And Impairments",
        "selectable": false,
        "sub_type": "ability",
        "sub_type_pretty": "Ability",
        "name": "Dormenatus",
        "desc": "When you suffer damage, you may declare 'Dormenatus X' in a loud, booming voice. If you do, gain <font class=\"inline_shield\">x</font> to each hit location. X cannot be more than your total green affinities. After the damage is resolved, gain +X hunt XP.<br/>When you trigger Age 2, gain the <b>Grace of Dormenatus</b> secret fighting art.",
        "type": "abilities_and_impairments"
    },
    "dream_of_the_beast": {
        "Strength": 1,
        "handle": "dream_of_the_beast",
        "name": "Dream of the Beast",
        "max": 1,
        "epithet": "red_savior",
        "related": [
            "caratosis",
            "life_exchange"
        ],
        "sub_type": "ability",
        "type_pretty": "Abilities And Impairments",
        "affinities": {
            "red": 1
        },
        "sub_type_pretty": "Ability",
        "type": "abilities_and_impairments",
        "selectable": false,
        "desc": "1 permanent red affinity."
    },
```

In the legacy app, I hide all of the savior attributes (i.e. filter on the `selectable` attrib) and then use the `/survivor/set_savior_status/<oid>` route to set the savior 'color', which then adds all of these (or removes them, if you change the savior to a different 'color' or unset the savior's savior status.

I'll punch up the docs in the next release so that the endpoint makes more sense.

**Comment by CalebKester** [comment]
@toconnell @lajollagrad  thanks guys! I think all that needs to happen is this should force a refresh of the data. I added Dream of the Beast, and then I hit f5 and this is what it shows up:

![image](https://user-images.githubusercontent.com/1319995/33964645-b5aabf02-e01e-11e7-9289-eb03cd0e735f.png)

Is this what you would expect?

**Comment by CalebKester** [comment]
I got the fix in for this. Go ahead and reopen this if this didn't fix it @lajollagrad  thanks again for the report!
