### ISSUE TITLE
Glossary/FAQ Search/Pagination

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#23]
I have our Glossary/FAQ page loading up all/slice of our data.

We need to tie in a search to filter the titles of the data. Also should probably tie in a pagination tool so we can make it easier for the user to see the results. 

Maybe tie this in? https://github.com/AdeleD/react-paginate

I think probably the best solution for now is to treat this more as a filter then a search. Show all the results then limit it down as you type. But up to you.

**Comment by Chibird12** [comment]
I removed pagination and just had it filtering on type. Tried to get stuff to highlight but it wasnt working will need to do it in another ticket.
