### ISSUE TITLE
Promise and Props

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#3]
`<Survival number={Number(this.state.survivorData.survival)} survivalLimit={this.state.settlementData.sheet.survival_limit} />`

Found in World.jsx is throwing an error due to the settlementData not existing. 

```
World.jsx:51 Uncaught (in promise) TypeError: Cannot read property 'sheet' of null
    at World.render (World.jsx:51)
    at ReactCompositeComponent.js:796
```

It doesn't do it for the survival data so i just assume we're missing something with the settlementData sheet

**Comment by Chibird12** [comment]
will clean up as we go
