### ISSUE TITLE
Set Page Heading

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#37]
We need a way to set the name that shows at the top of the page. The controlling component for the Page Heading is `components\Header\Header.jsx`

The page to start on will be the campaign log page: `http://localhost:3333/settlements/1234/log` found here: `\containers\Log\Log.jsx` I would like the header to say "Campaign Log"

See red area here to see where the text should be: http://i.imgur.com/haMzq9K.png

**Comment by Chibird12** [comment]
didnt really understand this ticket too well, but i changed the name to "Campaign Log" as requested. Header names are managed in routes.jsx, every route has a title and thats what the header titles are
