### ISSUE TITLE
Campaign Log Data

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#38]
We need to populate the campaign log page with data: http://i.imgur.com/0rgW0Mz.png

http://localhost:3333/settlements/1234/log

Most important
- [ ] Name
- [ ] Lantern Year
- [ ] Pop
- [ ] Milestones

Nice to haves (don't spend too much time trying to figure out the data.
- [ ] Most Recent Milestone
- [ ] Most Recent Death
- [ ] Most Recent Birth
- [ ] Most Recent Monster Quarry
- [ ] Last 5 logs

If you can't get the nice to have data that's fine, we'll hold off until later.

**Comment by Chibird12** [comment]
did what i could, and flowed data into log.jsx

Things to note: 
1) Last 5 logs, recent death, and recent birth is difficult
2) as with everything if you refresh or this is your first time hitting the app it needs to call the data and takes a few seconds to load, perhaps we should impliment a loader
