### ISSUE TITLE
Create Settlement Routes

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#43]
@toconnell we need to get the create settlement routes up and start setting up the save routes.

Let us know when you have some time to help on it.

**Comment by toconnell** [comment]
@CalebKester Hey--was there a specific route that was giving you all trouble? Most of the settlement get/set/update routes are working pretty well in the legacy web app.

**Comment by toconnell** [comment]
@Chibird12 When I do `/new/settlement` hits from the legacy app, here's my vanilla POST body (just for reference):

```
{u'survivors': [], u'specials': [], u'expansions': [], u'name': None, u'campaign': u'people_of_the_lantern'}
```

**Comment by toconnell** [comment]
@Chibird12 's first request from the app that died upon init makes me wonder if I haven't got a bug somewhere in the new settlement method.

In the API logs, he made it to here:

```
[2017-09-12 16:00:20] DEBUG:    [kaythxs@gmail.com (57ee63138740d9717d8bb584)] is requesting a new 'settlement' asset!
[2017-09-12 16:00:20] INFO:     [kaythxs@gmail.com (57ee63138740d9717d8bb584)] creating a new settlement...
[2017-09-12 16:00:20] DEBUG:    [kaythxs@gmail.com (57ee63138740d9717d8bb584)] new settlement params: {}
```

...and then his request died and he got a 500 back, which makes me think I'm doing something wrong/bad when I don't get params. I'm going to check that out today.

**Comment by CalebKester** [comment]
@toconnell @Chibird12 Where are we at with this? Can I help either of you 2 diagnose this or figure it out?

**Comment by toconnell** [comment]
@CalebKester Well, no progress as such, but I was taking a look at an intermittent issue causing API load failures in the production legacy webapp (https://github.com/toconnell/kdm-manager/issues/265) this morning and I noticed that in certain browsers/contexts you could get a CORS failure if you tried to hit the _/settlement/get/<oid>_ route under certain conditions. 

I'm going to do a quick release today or tomorrow of break/fix stuff that includes explicitly permitting the CORS 'Access-Control-Allow-Origin' header for all routes that could potentially do a CORS check.

I'm not sure if they're the same problem, but it might have a positive effect.

**Comment by Chibird12** [comment]
hey @toconnell, what do you think about removing the authorization in the header completely and i just send you a userId in the body? We can always add it back when we find out the issue yeah? I don't think anyone is gonna hack the app.

**Comment by toconnell** [comment]
@Chibird12 Well, cutting the JWT stuff now is kind of hard to do, since its wired into...pretty much everything that I've done since we settled on it back in January haha.

Which, to be serious for a minute, I should say that I could probably make JWT in the header optional pretty easily, but there's a lot of application logging and user-facing stuff that uses the JWT info, etc. that would be a PITA to refactor and probably could not be done quickly.

Is it really the "Authorization" header thing that's giving you trouble now? And if so, is that what's blocking you from hitting _/new/settlement_ ? 

If that's the case, I haven't really been looking at it from that angle, and that's actually a pretty important insight. 

Either way, let me know.

**Comment by toconnell** [comment]
Documenting private Slack chats for future reference:

![user_oid_backoff](https://user-images.githubusercontent.com/48043/30617422-9ac2b0ba-9d5b-11e7-97ea-f921df55d587.PNG)

@CalebKester We just had a long chat about a workaround and I'm going to get it implemented for the next release. @Chibird12 and I will be in touch once it's running in production and looks like it's working.

**Comment by CalebKester** [comment]
Great work guys! Glad to hear it!

**Comment by toconnell** [comment]
As of right now, token-less/workaround auth looks like it's working:

![great_success](https://user-images.githubusercontent.com/48043/30747961-667f00a4-9f74-11e7-912e-7f6b69418cba.PNG)

**Comment by toconnell** [comment]
@CalebKester  As soon as you're able to verify that you can create, this one is probably good to close out, but let me know if you see any weirdness.

**Comment by CalebKester** [comment]
@toconnell  @Chibird12 looks like this is working! Now #46 will track actually getting the interface working and hooking up data to it.
