### ISSUE TITLE
Beta Checklist

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#44]
## App Functionality
- [ ] Create Account
/new/user - works w/ CORS in API release 0.55.442
- [ ] Create Settlement
/new/settlement 
- [x] Change Active Settlement
/user/set/<user_id> (read the docs on this one; it needs specific stuff in the POST body)
- [x] Create Survivor
/new/survivor

## Settlement Functionality
- [ ] Settlement Notes
TBD
- [ ] Settlement event log
/settlement/get_event_log/<settlement_id>
Update routes TBD
- [ ] Departing Survivors
coming soon/TBD

## Survivor Functionality
- [ ] Survival
/survivor/update_survival/<survivor_id>
/survivor/set_survival/<survivor_id>
- [ ] Bleeding
TBD

**Attributes:**
- [ ] XP
- [ ] Courage
- [ ] Understanding
- [ ] Primary Stats
/survivor/set_attribute/<survivor_id>
/survivor/update_attribute/<survivor_id>
- [ ] Weapon
/survivor/set_weapon_proficiency_type/<survivor_id>
- [ ] Armor
coming soon

**Game Assets:**
- [ ] Fighting Arts
supported in API release  0.54.429 and later
/survivor/add_game_asset<survivor_id>
/survivor/rm_game_asset/<survivor_id>
- [ ] Disorders
coming soon
- [ ] Abilities & Impairments
supported in API release 0.52.396 and later
/survivor/add_game_asset/<survivor_id>
/survivor/rm_game_asset/<survivor_id>

**Meta elements**
- [ ] Survivor Notes
coming soon

**Misc. UI**
- [ ] Kill Survivor
/survivor/controls_of_death/<survivor_id> (definitely read the docs on this one)

**Comment by toconnell** [comment]
I just touched this up to reflect some recent API enhancements and to clarify some of my more cryptic comments.

**Comment by CalebKester** [comment]
I'm going to close this. We're basically there and I'll branch what's not done in other tickets
