### ISSUE TITLE
Load settlement data up

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#49]
Need settlement data in this page: http://thewatcher.surge.sh/settlements/58a67a858740d973ab1ba457/settlement

**Comment by CalebKester** [comment]
@Chibird12 if I cycle through the tabs it will keep loading up the settlement page. Should we have it check to see if there's already data there and not make the api call if it doesn't need ot?

**Comment by Chibird12** [comment]
TLDR: Dashboard component is the settlements component as well as the wrapper component.

Solutions:
1) Change settlements component
2) Not wrap everything in dashboard component
![screen shot 2017-10-11 at 5 58 33 am](https://user-images.githubusercontent.com/8093447/31441942-a10f0898-ae49-11e7-98fb-4354affcec34.png)

**Comment by Chibird12** [comment]
The settlements api call only happens on settlements and survivors, needs to happen in case the user refreshes the page
