### ISSUE TITLE
Survivor Attributes saving

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#51]
We need to start saving survivor attributes.

- [ ] Survival
- [x] Bleeding
- [ ] XP
- [ ] Courage
- [ ] Understanding
- [ ] Weapon
- [x] Primary Stats
- [ ] Assets (see comment below)

I've created self contained components under /containers/Survivor . Look at _Bleeding . We need to tie this to the `/survivor/update_bleeding_tokens/<survivor_id>` api call.

If you can get this one working I can try and use this as an example and do the other ones. I know you got on you and the create functions I'm sure are a lot of work.

**Comment by Chibird12** [comment]
will be done saturday with Tim's new api push

**Comment by CalebKester** [comment]
@toconnell Did your new api push succeed? What do we need to start saving survivor attributes?

**Comment by toconnell** [comment]
Yeah, `/survivor/set_bleeding_tokens/<survivor_id>` will go out in the next release. 

[edit: next release is going to be tonight]

For every other attribute on the Sheet (except one or two), you want to use `/survivor/set_attribute/<survivor_id>` or `/survivor/update_attribute/<survivor_id>` (both of which already work and have been in production for a few releases, so they're pretty well burned-in).

**Comment by toconnell** [comment]
>  22 files changed, 1458 insertions(+), 1099 deletions(-)

@CalebKester and @Chibird12: I just pushed the release that adds `set_bleeding_tokens`.

Holler!

**Comment by CalebKester** [comment]
Sweet, this is on @Chibird12  to work on then! Thanks!

**Comment by CalebKester** [comment]
@Chibird12 so I think with Tim's latest route we can knockout all of our _assets (FA/disorder/abilities/impairments/severeinjuries) with one simple api call. Checkout the handleConfirm method. I have a console.warn that shows the route and data that it should hit. All you need to do is to put this in redux :)

**Comment by CalebKester** [comment]
tested this all. I think we're golden.
