### ISSUE TITLE
Changing Active Settlement Errors out

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#54]
When I try and change my active settlement I get an api error: http://thewatcher.surge.sh/settlements

Could you check the call make sure it matches what should be in the api call and if all looks good send this to Tim?

Thanks

**Comment by CalebKester** [comment]
```Failed to load http://api.thewatcher.io/user/set/57b9e779421aa903403a7432: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3333' is therefore not allowed access. The response had HTTP status code 400.```

**Comment by toconnell** [comment]
hey @Chibird12 I think this is PROBABLY an unhandled exception on my side. Can you paste me the JSON you're POSTing so I can try to run it down?

**Comment by CalebKester** [comment]
Thanks Tim! Changed it to post and it worked!
