### ISSUE TITLE
Severe Injuries

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#56]
- Are we validating this list? e.g. multiple of the same type that's limit to once?
- Should we add x 2 to repeat severe injuries instead of repeating twice? (yes, because gear will use this)

**Comment by toconnell** [comment]
Hey @CalebKester the API actually does this.

Try using `/survivor/add_game_asset/<survivor_id>` to post something like, `{type: 'abilities_and_impairments', handle: 'blind'} to a survivor, reload it (check out the `Accuracy` stat) and then try posting it again...and again. 

If you look at the `game_assets` of the serialized Settlement, you'll notice that certain types of A&Is have the `type` of 'severe_injury': these all have a max and automatically "damage" (i.e. update survivors stats) when you call `add_game_asset()`
