### ISSUE TITLE
User Login API Calls

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#74]
I wanted to outline the steps that we need to do for when the user logins.

Business Requirements:

1. User Logins
2. User gets taken to their current settlement.

API Steps (update this as needed)

1. User enters their information and hits login. START LOADING SCREEN
2. POST to `/login`
3. On success send a new GET to `/user/dashboard/<OID>`
4. On success pull their user.current_settlement.$oid.
5. Redirect them to `settlements/<oid>`

When a settlement route is hit, always check to see if if we have settlement data. if not, pull it:
1. `/settlement/get/<OID>`

**Comment by toconnell** [comment]
@CalebKester I just made a couple of minor corrections to the URLs.

One thing worth mentioning that if you're to do the two-route settlement retrieval thing, you should A/B that (in terms of performance) versus just going whole hog and sending a GET to `/settlement/get/<OID>` and seeing which way is actually faster.

I honestly don't know which method will perform better, so I think it's worth experimenting with both.

**Comment by CalebKester** [comment]
Thanks @Chibird12 !
