### ISSUE TITLE
Newly registered user not authenticated

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#82]
When I create a new account and try and create a settlement I get an error saying the user isn't authenticated. However if I f5 and refresh the page it's fine.

My guess is we are missing the dashboard api call or another api call that sets the access token.

**Comment by Chibird12** [comment]
need a token in the response when a user is create

**Comment by CalebKester** [comment]
@toconnell can we get a token on new registered user response?

**Comment by toconnell** [comment]
Sure. I'll get that in the next release.

Working it here: https://github.com/toconnell/kdm-manager/issues/404

**Comment by toconnell** [comment]
Actually, it was easier than I thought. It's done, I closed toconnell/kdm-manager#404 and it will go out in the next release.
