### ISSUE TITLE
[API Request] Enhanced Log

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#87]
After my test drive of the app last night we felt that a good log might be a nice update to do.

Here's the design that Logan sent me a few weeks ago. Since it didn't match the api didn't do anything with it but after playing last night I realized it might be good to start dreaming some nice improvements.
![image](https://user-images.githubusercontent.com/1319995/32985756-2d8279f8-cc87-11e7-8543-4f700678df0e.png)

Wishlist

- Filter by type
- - Settlement
- - Survivors - To be used in the screenshot above
- - Survivor - To be used on that specific survivor's page
- `get_latest_event_log`. Pass a datetimestamp or the oid of the last event and only get the logs after that point.

Let me know your thoughts.

**Comment by toconnell** [comment]
Event log lines have types: the easiest thing to do to achieve your first two bullets would be to look for the `event_type` key in the individual line and filter accordingly.

For the third thing, I will update the way logging works so that survivor-specific events get tagged with a survivor oid: https://github.com/toconnell/kdm-manager/issues/418 

For the fourth one, let's go on OIDs, since datetime stamps and javascript are...known to cause issues. I'll update the `get_event_log()` syntax so that it takes an OID and gives you everything AFTER that OID: https://github.com/toconnell/kdm-manager/issues/419

**Comment by CalebKester** [comment]
@toconnell these sound awesome. You made it sound really easy too ;) Do you know when  you could get this done by? No pressure but just trying to decide if this should go in Alpha Phase 1

**Comment by toconnell** [comment]
@CalebKester Hey brosef: toconnell/kdm-manager#419 is going out in the next API release and it will update the _get_event_log_ endpoint thus:

![update_get_event_log](https://user-images.githubusercontent.com/48043/33044165-6946ef78-ce0d-11e7-8d9a-c7b626138c5e.PNG)

**Comment by toconnell** [comment]
@CalebKester Survivor-specific events will be tagged with the OID of the survivor in the next release:

![survivor_oid_in_event_log](https://user-images.githubusercontent.com/48043/33044773-d1227f84-ce0f-11e7-8a20-1991ddd0a28e.PNG)

**Comment by toconnell** [comment]
Hey, also, @CalebKester and @Chibird12 , if you want, I can update _get_event_log_ to let you query on a specific survivor OID. 

Any interest in that?

**Comment by CalebKester** [comment]
Sure that would work well too!

**Comment by toconnell** [comment]
@CalebKester toconnell/kdm-manager#418 and toconnell/kdm-manager#419 went out last night.

I'm going to start pulling things in for another release...maybe on/after Thanksgiving that includes the survivor OID query hooks.

**Comment by toconnell** [comment]
Hey @Chibird12  and @CalebKester I just wrapped up https://github.com/toconnell/kdm-manager/issues/422 and I'm going to roll it out in the next release (i.e. the everything-finally-supports-SSL release, which I want to do tonight).

Also, when it goes out, the _/survivor/get_lineage/oid_ route will also be touched up and will return a survivor's private event log (under the `events` element, which will be reverse-chron a list of log lines).

Holler!

**Comment by toconnell** [comment]
Alright, my Glib-Globs: I just rolled this release out, so you can scope down the event log three ways now:

![get_event_log_docs](https://user-images.githubusercontent.com/48043/33099219-c2dd7a02-ced5-11e7-8f08-12038781ee69.PNG)

**Comment by CalebKester** [comment]
@Chibird12 we need to update the log page with this functionality so we just pull the newest information
