### ISSUE TITLE
Population/Death count

### ISSUE THREAD

**Issue by paddirn** [Playing-Indoors/KDM_WWW#93]
On iOS, killing a survivor does not cause the Population counter or Death Count to update on the Settlement page. In my case, have 5 survivors, then killed one. Population still shows '5' and Death Count reads '0'.

**Comment by paddirn** [comment]
Though, the 'Survivors' page does show the dead Survivor as indeed Dead, the Alive vs Dead numbers are accurate.

**Comment by paddirn** [comment]
Actually, it's not accurate. Alive still reads '5' (only 4 actually listed), but Dead does actually show '1' dead.

**Comment by toconnell** [comment]
@paddirn Thanks for opening this!

I actually got a couple of emails about it last week from kdm-manager.com users and I was going to look at it this week, i.e. for inclusion in the next release.

@CalebKester This one's on me: I'm working it now.

**Comment by CalebKester** [comment]
Ah yeah I figured you were doing some voodoo magic on this. I had to parse it know survivor page. For the watcher this is a very low priority. Getting it done anytime soon isn't too high of priority since it's just settlement data.

**Comment by toconnell** [comment]
Linked to https://github.com/toconnell/kdm-manager/issues/426, which I'm going to start working...right now!

@paddirn

**Comment by toconnell** [comment]
toconnell/kdm-manager#426 is resolved. The fix is going out in the next release...I'll leave this one open, however, so @CalebKester can keep it on the radar for when we move into settlement/campaign UX.

**Comment by CalebKester** [comment]
I'll close this. If your stuff works it'll be good to go.
