### ISSUE TITLE
Request: App navigation always present

### ISSUE THREAD

**Issue by Kedoch** [Playing-Indoors/KDM_WWW#97]
It would be nice to be able to always see the master navigation pain at the bottom of the screen no matter what sub-section I am in (e.g. survivors or innovations) to allow one to quickly return to the main navigational screens rapidly and easily without first having to back out of everything.

At last I think that would be pretty well, if feasible.

**Comment by CalebKester** [comment]
Hi Kedoch,

I'm putting this on our feature request list and I'll talk things over with our designer on this. Some of these will stay but we might open it up a little bit as well. We really need to hash out the flow of the app once we get more functionality in there.

The survivors screen will stay without it as we want to maximize the amount of space you have to view the survivor. This will be easier to manage when we build in desktop mode as well as building a survivor hunt party.
